def pin_extractor(poems):
    """
    Extracts a secret code (PIN) from each poem in a list.

    The code is generated by taking the length of the N-th word in the N-th line.
    (N starts at 0 for the first line/word). If the line is too short, '0' is used.

    Args:
        poems (list of str): A list where each string is a poem.

    Returns:
        list of str: A list of the extracted secret codes (strings of digits).
    """
    secret_codes = []
    
    # Iterate through each poem in the input list
    for poem in poems:
        secret_code = ''
        
        # Split the poem string into a list of individual lines
        lines = poem.split('\n')
        
        # Iterate through the lines, using enumerate to get both the index (line_index)
        # and the line content. line_index corresponds to N in the logic (0, 1, 2, ...).
        for line_index, line in enumerate(lines):
            
            # Split the line into a list of words based on whitespace
            words = line.split()
            
            # Check if the line has at least 'line_index + 1' words (the N-th word, 
            # where N starts at 0). E.g., for line_index 0, check if len(words) > 0.
            if len(words) > line_index:
                
                # Get the N-th word (word at the current line_index)
                target_word = words[line_index]
                
                # Append the length of the target word as a string digit to the secret code
                secret_code += str(len(target_word))
            else:
                # If the line is too short to contain the N-th word, append '0'
                secret_code += '0'
                
        # After processing all lines in the poem, add the generated code to the list
        secret_codes.append(secret_code)
        
    return secret_codes

# --- Example Usage ---

poem = """Stars and the moon
shine in the sky
white and
until the end of the night"""

poem2 = 'The grass is green\nhere and there\nhoping for rain\nbefore it turns yellow'
poem3 = 'There\nonce\nwas\na\ndragon'

# Example of how to call the function:
# print(pin_extractor([poem, poem2, poem3])) 
# Output for the example poems: ['5205', '3366', '54316']